/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package br.com.julio.CampoMinado;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    
    @Test
    void testaEPar() {
        
        int a = 1 + 1;
        assertEquals(2, a);
    }
    
    @Test
    void testaIgualTres() {
        
        int x = 2 + 7 - 6;
        assertEquals(3, x);
}
}
